// Generated by https://quicktype.io

export interface RentalListItemDto {
    id:       number;
    customer: Customer;
    car:      Car;
}

export interface Car {
    id:    number;
    plate: string;
}

export interface Customer {
    id:        number;
    firstName: string;
    lastName:  string;
}
